# Generated by Django 5.0.7 on 2025-11-25 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_cameraconfiguration_success_sound_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cameraconfiguration',
            name='post_minutes',
            field=models.IntegerField(default=5, help_text='Keep camera active N minutes after timetable end'),
        ),
        migrations.AddField(
            model_name='cameraconfiguration',
            name='pre_minutes',
            field=models.IntegerField(default=5, help_text='Activate camera N minutes before timetable start'),
        ),
        migrations.AddField(
            model_name='cameraconfiguration',
            name='schedule_enabled',
            field=models.BooleanField(default=False, help_text='Enable schedule-based activation'),
        ),
        migrations.AlterField(
            model_name='cameraconfiguration',
            name='threshold',
            field=models.FloatField(default=0.8, help_text='Face recognition confidence threshold (0.7-0.9 recommended)'),
        ),
        migrations.AddField(
            model_name='cameraconfiguration',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classroom'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pre_minutes', models.IntegerField(blank=True, null=True)),
                ('post_minutes', models.IntegerField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.classroom')),
            ],
        ),
    ]
