# Generated by Django 5.0.7 on 2025-11-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_classroom_cameraconfiguration_post_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraconfiguration',
            name='motion_threshold',
            field=models.IntegerField(default=2000, help_text='Number of changed pixels to consider motion detected'),
        ),
    ]
